### ISSUE TITLE
Query regarding support for "Chameleon", "Cornell", "Texas" and "Wisconsin" datasets

### ISSUE THREAD

**Issue by venomouscyanide** [DaDaCheng/WalkPooling#2]
Dear Authors, 

Thank you for sharing the codebase for WalkPool and promoting results reproducibility in your experiments. However, I noticed that the codebase currently has no support for the following datasets reported in the paper: "Chameleon", "Cornell", "Texas" and "Wisconsin". Could you please let me know if there are plans to update the repository with these datasets as well?

Warm Regards,
Paul Louis

**Comment by DaDaCheng** [comment]
Hi Paul,

Thanks for reading our paper. These datasets have been uploaded.

Best
Cheng
