### ISSUE TITLE
Missing SPC initialization codes?

### ISSUE THREAD

**Issue by venomouscyanide** [DaDaCheng/WalkPooling#3]
Dear Authors,

I was going through the possible options of initializing node attributes in WalkPool. I noticed SPC clustering (https://github.com/DaDaCheng/WalkPooling/blob/main/src/utils.py#L340) is an option to initialize node attributes for datasets. However, I could not find the code for SPC. 

Could you please let me know how to use SPC as initial node attributes for WalkPool? Please let me know if I am running the program incorrectly.

Warm Regards,
Paul

**Comment by DaDaCheng** [comment]
Hi Paul,

Thanks for your interest in our work.   

I have uploaded the SPC.py.

Best,
Cheng

**Comment by venomouscyanide** [comment]
Thank you!
